apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: 395127550274.dkr.ecr.ap-northeast-1.amazonaws.com/infra-bot-sandbox/get-servers-num:66c5ec9
          imagePullPolicy: Always

