namePrefix: kustomize-

resources:
- bot-deployment.yaml
- bot-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ./bots/hello/
  newName: /infra-bot-sandbox/hello
