apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  infra-bot.yaml: |-
    token: bG9jYWxob3N0
    ansible:
      slack_notify_channel: "#prd-all-ansible-sandbox"
      bucketname: rf-sandbox-ansiblelog
      playbook: deploy_sandbox.yml
      playbook_db_import: db_restore_sandbox.yml
      inventory: inventory-sandbox
      domain: readyfor-sandbox.jp
      env: sandbox
