apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: mysecret-volume
              mountPath: "/etc/mysecret.d"
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: example-config
        - name: mysecret-volume
          secret:
            secretName: mysecret
