apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: nginx:1.19-alpine
          imagePullPolicy: Always

