namePrefix: kustomize-

resources:
- bot-deployment.yaml
- bot-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: redis
- name: redis
  newName: nginx
