name: Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build-push:

    name: build-push
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1    

    - name: Docker Build
      run: |
        bash .github/workflows/scripts/build.sh

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr-sandbox
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.8.7"

    - name: Docker tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-sandbox.outputs.registry }}
      run: |
        bash .github/workflows/scripts/tag-push.sh $ECR_REGISTRY sandbox

    - name: Commit files
      run: |
        git config --local user.email "tomokazu.hirai@gmail.com"
        git config --local user.name "Tomokazu HIRAI"
        git commit -am "Bump docker tag"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
